### **INDEX**
1. Setup Notebook
2. Following Along Exercise
3. Exercise Directions

 . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .

### **1. SETUP NOTEBOOK**

In [5]:
# import libraries
import pandas as pd
import numpy as np
import os
from pathlib import Path

In [6]:
# get the current working directory as a Path object
path = os.getcwd()

# update the path to parent folder
path = os.path.abspath(os.path.join(path, os.pardir))

In [7]:
# import orders products merged
df_ords_prods_merge  = pd.read_pickle(os.path.join(path, '02 Data', 'Prepared Data', 'ords_prods_merge.pkl'))

In [8]:
df_ords_prods_merge.head()

,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_last_order,First_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,_merge
0,1,1,2,8,NaN,True,196,1,0,Soda,77,7,9.0,both
1,1,1,2,8,NaN,True,14084,2,0,Organic Unsweetened Vanilla Almond Milk,91,16,12.5,both
2,1,1,2,8,NaN,True,12427,3,0,Original Beef Jerky,23,19,4.4,both
3,1,1,2,8,NaN,True,26088,4,0,Aged White Cheddar Popcorn,23,19,4.7,both
4,1,1,2,8,NaN,True,26405,5,0,XL Pick-A-Size Paper Towel Rolls,54,17,1.0,both

 . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .

### **2. FOLLOW ALONG EXERCISE**

In [11]:
#create subset 
df_subset = df_ords_prods_merge[:1000000]

**New column: Price Range on subset**

In [13]:
#create if+user-function with price range lable
def price_label(row):

  if row['prices'] <= 5:
    return 'Low-range product'
  elif (row['prices'] > 5) and (row['prices'] <= 15):
    return 'Mid-range product'
  elif row['prices'] > 15:
    return 'High range'
  else: return 'Not enough data'

In [14]:
#apply function 
df_subset['price_range'] = df_subset.apply(price_label, axis=1)

/var/folders/bd/qhxglvhx1rq8bqtllnl7lp800000gn/T/ipykernel_9798/3802199539.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_subset['price_range'] = df_subset.apply(price_label, axis=1)

In [15]:
df_subset['price_range'].value_counts(dropna = False)

price_range
Mid-range product    673183
Low-range product    314392
High range            12425
Name: count, dtype: int64

In [16]:
df_subset.head()

,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_last_order,First_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,_merge,price_range
0,1,1,2,8,NaN,True,196,1,0,Soda,77,7,9.0,both,Mid-range product
1,1,1,2,8,NaN,True,14084,2,0,Organic Unsweetened Vanilla Almond Milk,91,16,12.5,both,Mid-range product
2,1,1,2,8,NaN,True,12427,3,0,Original Beef Jerky,23,19,4.4,both,Low-range product
3,1,1,2,8,NaN,True,26088,4,0,Aged White Cheddar Popcorn,23,19,4.7,both,Low-range product
4,1,1,2,8,NaN,True,26405,5,0,XL Pick-A-Size Paper Towel Rolls,54,17,1.0,both,Low-range product

In [17]:
#create if+loc with price range lable
df_subset.loc[df_subset['prices'] > 15, 'price_range_loc'] = 'High-range product'

/var/folders/bd/qhxglvhx1rq8bqtllnl7lp800000gn/T/ipykernel_9798/2766284883.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_subset.loc[df_subset['prices'] > 15, 'price_range_loc'] = 'High-range product'

In [18]:
df_subset.loc[(df_subset['prices'] <= 15) & (df_subset['prices'] > 5), 'price_range_loc'] = 'Mid-range product'

In [19]:
df_subset.loc[df_subset['prices'] <= 5, 'price_range_loc'] = 'Low-range product'

In [20]:
df_subset['price_range_loc'].value_counts(dropna = False)

price_range_loc
Mid-range product     673183
Low-range product     314392
High-range product     12425
Name: count, dtype: int64

**New Column: Busy days on dataframe**

In [22]:
# Find order frequency by day
df_ords_prods_merge['orders_day_of_week'].value_counts(dropna=False)

orders_day_of_week
0    6204182
1    5660230
6    4496490
2    4213830
5    4205791
3    3840534
4    3783802
Name: count, dtype: int64

In [23]:
#create loop
result = []

for value in df_ords_prods_merge["orders_day_of_week"]:
  if value == 0:
    result.append("Busiest day")
  elif value == 4:
    result.append("Least busy")
  else:
    result.append("Regularly busy")

In [24]:
#embed results in dataframe
df_ords_prods_merge['busiest_day']=result

In [25]:
df_ords_prods_merge['busiest_day'].value_counts(dropna=False)

busiest_day
Regularly busy    22416875
Busiest day        6204182
Least busy         3783802
Name: count, dtype: int64

 . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .

### **3. EXERCISE DIRECTIONS**

**Dir 1. Both columns created above. Price Label is applied to the subset-dataframe and Busiest Day is applied on the whole dataframe**

**Dir 2: Find 2 busiest and slowest days and adjust labels in a new column**

In [30]:
#find business of days 
df_ords_prods_merge['orders_day_of_week'].value_counts(dropna=False)

orders_day_of_week
0    6204182
1    5660230
6    4496490
2    4213830
5    4205791
3    3840534
4    3783802
Name: count, dtype: int64

> **Answer 2: Busiest days are 0 and 1, corresponding to 0 = Saturday and 1 = Sunday. Least busy days are 3 and 3, corresponding to 3 = Tuesday and 4 = Wednesday**

In [32]:
#reapply label on busiest days
result = []

for value in df_ords_prods_merge["orders_day_of_week"]:
  if value in [0, 1]:
    result.append("Busiest days")
  elif value in [3, 4]:
    result.append("Least busy days")
  else:
    result.append("Regularly busy day")

In [33]:
#confirm output 
result

['Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Least busy days',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',
 'Regularly busy day',

In [34]:
#embed new column in dataframe
df_ords_prods_merge['busy_days']=result

In [35]:
#confirm embed
df_ords_prods_merge.head()

,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_last_order,First_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,_merge,busiest_day,busy_days
0,1,1,2,8,NaN,True,196,1,0,Soda,77,7,9.0,both,Regularly busy,Regularly busy day
1,1,1,2,8,NaN,True,14084,2,0,Organic Unsweetened Vanilla Almond Milk,91,16,12.5,both,Regularly busy,Regularly busy day
2,1,1,2,8,NaN,True,12427,3,0,Original Beef Jerky,23,19,4.4,both,Regularly busy,Regularly busy day
3,1,1,2,8,NaN,True,26088,4,0,Aged White Cheddar Popcorn,23,19,4.7,both,Regularly busy,Regularly busy day
4,1,1,2,8,NaN,True,26405,5,0,XL Pick-A-Size Paper Towel Rolls,54,17,1.0,both,Regularly busy,Regularly busy day

**Dir 3: Check the values of this new column for accuracy. Note any observations in markdown format**

In [37]:
#count busy days
df_ords_prods_merge['busy_days'].value_counts(dropna=False)

busy_days
Regularly busy day    12916111
Busiest days          11864412
Least busy days        7624336
Name: count, dtype: int64

> **Observations: I recommend adjusting this label to specify which and how many days are included in the busiest and slowest days.**

**Dir 4: Label times of the day by order frequency.**

In [40]:
#count busy hours
df_ords_prods_merge['order_hour_of_day'].value_counts(dropna=False)

order_hour_of_day
10    2761760
11    2736140
14    2689136
15    2662144
13    2660954
12    2618532
16    2535202
9     2454203
17    2087654
8     1718118
18    1636502
19    1258305
20     976156
7      891054
21     795637
22     634225
23     402316
6      290493
0      218769
1      115700
5       87961
2       69375
4       53242
3       51281
Name: count, dtype: int64

In [41]:
#create loop
outcome = []

for value in df_ords_prods_merge['order_hour_of_day']:
  if value in [10, 11,14,15,13,12,16,9]:
    outcome.append("Fewest orders")
  elif value in [3,4,2,5,11,0,6,23]:
    outcome.append("Most orders")
  else:
    outcome.append("Average orders")

In [42]:
#embed new column in dataframe
df_ords_prods_merge['busiest_period_of_day']=outcome

In [43]:
#confirm embed
df_ords_prods_merge.head()

,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_last_order,First_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,_merge,busiest_day,busy_days,busiest_period_of_day
0,1,1,2,8,NaN,True,196,1,0,Soda,77,7,9.0,both,Regularly busy,Regularly busy day,Average orders
1,1,1,2,8,NaN,True,14084,2,0,Organic Unsweetened Vanilla Almond Milk,91,16,12.5,both,Regularly busy,Regularly busy day,Average orders
2,1,1,2,8,NaN,True,12427,3,0,Original Beef Jerky,23,19,4.4,both,Regularly busy,Regularly busy day,Average orders
3,1,1,2,8,NaN,True,26088,4,0,Aged White Cheddar Popcorn,23,19,4.7,both,Regularly busy,Regularly busy day,Average orders
4,1,1,2,8,NaN,True,26405,5,0,XL Pick-A-Size Paper Towel Rolls,54,17,1.0,both,Regularly busy,Regularly busy day,Average orders

**Dir 5: Print frequency column**

In [45]:
df_ords_prods_merge['busiest_period_of_day'].value_counts(dropna=False)

busiest_period_of_day
Fewest orders     21118071
Average orders    10113351
Most orders        1173437
Name: count, dtype: int64

**Extra: Dropping the busiest_days column for table consistensy**

In [47]:
df_ords_prods_merge.drop(columns='busiest_day', inplace=True)

In [48]:
df_ords_prods_merge.head()

,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_last_order,First_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,_merge,busy_days,busiest_period_of_day
0,1,1,2,8,NaN,True,196,1,0,Soda,77,7,9.0,both,Regularly busy day,Average orders
1,1,1,2,8,NaN,True,14084,2,0,Organic Unsweetened Vanilla Almond Milk,91,16,12.5,both,Regularly busy day,Average orders
2,1,1,2,8,NaN,True,12427,3,0,Original Beef Jerky,23,19,4.4,both,Regularly busy day,Average orders
3,1,1,2,8,NaN,True,26088,4,0,Aged White Cheddar Popcorn,23,19,4.7,both,Regularly busy day,Average orders
4,1,1,2,8,NaN,True,26405,5,0,XL Pick-A-Size Paper Towel Rolls,54,17,1.0,both,Regularly busy day,Average orders

**Dir 7: Export your dataframe as a pickle file and store it correctly in your “Prepared Data” folder.**

In [50]:
#exporting df as pickle
df_ords_prods_merge.to_pickle(os.path.join(path, '02 Data','Prepared Data', 'ords_prods_merge.pkl'))